### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by IsraelOrtuno** [IsraelOrtuno/Propertier#26]
### Trivial

Things to get ready before release.
- [x] Add replace current from collections.
- [x] Delete previous values when replacing.
- [x] Delete values when set to null #4.
- [x] Convert to Array / Json #9.
- [x] Let create and delete attributes from Attribute Manager.
- [x] Support for `SoftDeleting` #22.
- [ ] Add indexes to migrations.
- [ ] Delete values when deleting entity / attribute.
- [ ] Enable default value support.
### Backlog

Things to implement in near future.
- [ ] Check for collisions between attribute names and model columns.
- [ ] Add value removal from collections.
- [ ] Improve performance adding more control when replacing collections to avoid deleting existing
- [ ] Let fill values from `fillableFromArray` method #21.
- [ ] Finish framework agnostic support.
- [ ] Upload sandbox app to repo.
### Wishlist

Things that will be nice to have in future.
- Attribute groups.
- Attribute order.
- Value content validation.
- Reduce queries when selecting.
- Support for multi-tenancy.
- Group insert queries in single query.
